language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install tensorflow==1.14
  - pip install -r requirements.txt
  - pip install .
  - pip install flake8
# command to run tests
script:
  - flake8
  - pytest

